/**
 * Maps AI SDK / Google Gemini errors into a clear, user-facing message.
 *
 * By default `toUIMessageStreamResponse()` masks stream errors as a generic
 * "An error occurred" for security, so we surface actionable guidance instead.
 * Reports are generated by Google Gemini directly (not the Vercel AI Gateway),
 * so authentication failures point at the GOOGLE_GENERATIVE_AI_API_KEY.
 */
export function formatAiStreamError(error: unknown): string {
  const message =
    error instanceof Error
      ? error.message
      : typeof error === "string"
        ? error
        : "";

  const lower = message.toLowerCase();

  if (lower.includes("google_generative_ai_api_key is not set")) {
    return message;
  }

  if (lower.includes("rate limit") || lower.includes("quota") || lower.includes("429")) {
    return "Google Gemini is rate limiting requests right now (free-tier quota). Please wait a moment and try again.";
  }

  if (
    lower.includes("api key") ||
    lower.includes("api_key_invalid") ||
    lower.includes("permission_denied") ||
    lower.includes("unauthorized") ||
    lower.includes("401") ||
    lower.includes("403")
  ) {
    return (
      "Google Gemini rejected the request — the GOOGLE_GENERATIVE_AI_API_KEY is missing or invalid. " +
      "Add a valid free key from https://aistudio.google.com/app/apikey to your project environment variables, then try again."
    );
  }

  return message || "The AI provider could not generate this report. Please try again.";
}
